name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # ðŸ‘‡ Sphinx build steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Graphviz
        uses: tlylt/install-graphviz@v1
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Build Sphinx Documentation
        run: |
          python -m venv env &&
          source env/bin/activate &&
          echo "VIRTUAL ENV:" $VIRTUAL_ENV &&
          cd sphinx/ &&
          pip3 install -r requirements.txt &&
          make html
      
      - name: Copy Sphinx output to Docusaurus static folder
        run: |
          mkdir -p the-site/static/sphinx
          cp -r sphinx/build/html/* the-site/static/sphinx/
      # ðŸ‘† Sphinx build steps
      
      # ðŸ‘‡ Docusaurus build steps
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: the-site/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./the-site
      - name: Build
        run: npm run build
        working-directory: ./the-site
      # ðŸ‘† Build steps
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the-site/build
          publish_branch: gh-pages
          keep_files: true