name: sphinx-preview

on: 
  push:
    branches: [sphinx-preview]
  workflow_dispatch:

# Sets permissions for pushing to gh-pages branch
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "sphinx-preview"
  cancel-in-progress: false

jobs:
  deploy-sphinx-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # ðŸ‘‡ Sphinx build steps only
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Graphviz
        uses: tlylt/install-graphviz@v1
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Build Sphinx Documentation
        run: |
          python -m venv env &&
          source env/bin/activate &&
          echo "VIRTUAL ENV:" $VIRTUAL_ENV &&
          cd sphinx/ &&
          pip3 install -r requirements.txt &&
          make html
      # ðŸ‘† Sphinx build steps
      
      - name: Deploy Sphinx to /sphinx subdirectory
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sphinx/build/html
          destination_dir: sphinx-preview/${{ github.sha }}
          publish_branch: gh-pages
          keep_files: true
