name: sphinx-preview

on: 
  push:
    branches: [sphinx-preview]
  workflow_dispatch:

# Sets permissions for pushing to gh-pages branch
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: "sphinx-preview"
  cancel-in-progress: false

jobs:
  deploy-sphinx-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: Checkout sphinx source from current branch
        uses: actions/checkout@v4
        with:
          path: source-repo
      
      # ðŸ‘‡ Sphinx build steps only
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Graphviz
        uses: tlylt/install-graphviz@v1
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Build Sphinx Documentation
        run: |
          python -m venv env &&
          source env/bin/activate &&
          echo "VIRTUAL ENV:" $VIRTUAL_ENV &&
          cd source-repo/sphinx/ &&
          pip3 install -r requirements.txt &&
          make html
      # ðŸ‘† Sphinx build steps
      
      - name: Update sphinx folder in gh-pages
        run: |
          rm -rf sphinx
          mkdir -p sphinx
          cp -r source-repo/sphinx/build/html/* sphinx/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sphinx
          git commit -m "Update sphinx documentation from ${{ github.sha }}" || echo "No changes to commit"
          git push
